###############################################################################
# Created by write_sdc
# Fri Dec 30 16:07:36 2022
###############################################################################
current_design cbx_1__1_
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name prog_clk -period 20.0000 [get_ports {prog_clk}]
set_clock_transition 0.1500 [get_clocks {prog_clk}]
set_clock_uncertainty 0.2500 prog_clk
set_propagated_clock [get_clocks {prog_clk}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {ccff_head}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[0]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[10]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[11]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[12]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[13]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[14]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[15]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[16]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[17]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[18]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[1]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[2]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[3]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[4]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[5]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[6]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[7]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[8]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_in[9]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[0]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[10]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[11]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[12]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[13]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[14]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[15]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[16]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[17]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[18]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[1]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[2]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[3]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[4]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[5]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[6]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[7]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[8]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_in[9]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {pReset}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {bottom_grid_top_width_0_height_0_subtile_0__pin_I_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {bottom_grid_top_width_0_height_0_subtile_0__pin_I_4_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {bottom_grid_top_width_0_height_0_subtile_0__pin_I_8_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {bottom_grid_top_width_0_height_0_subtile_0__pin_clk_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {ccff_tail}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[0]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[10]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[11]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[12]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[13]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[14]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[15]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[16]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[17]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[18]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[1]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[2]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[3]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[4]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[5]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[6]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[7]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[8]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_left_out[9]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[0]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[10]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[11]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[12]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[13]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[14]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[15]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[16]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[17]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[18]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[1]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[2]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[3]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[4]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[5]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[6]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[7]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[8]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chanx_right_out[9]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {top_grid_bottom_width_0_height_0_subtile_0__pin_I_10_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {top_grid_bottom_width_0_height_0_subtile_0__pin_I_2_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {top_grid_bottom_width_0_height_0_subtile_0__pin_I_6_}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {bottom_grid_top_width_0_height_0_subtile_0__pin_I_0_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_top_width_0_height_0_subtile_0__pin_I_4_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_top_width_0_height_0_subtile_0__pin_I_8_}]
set_load -pin_load 0.0334 [get_ports {bottom_grid_top_width_0_height_0_subtile_0__pin_clk_0_}]
set_load -pin_load 0.0334 [get_ports {ccff_tail}]
set_load -pin_load 0.0334 [get_ports {top_grid_bottom_width_0_height_0_subtile_0__pin_I_10_}]
set_load -pin_load 0.0334 [get_ports {top_grid_bottom_width_0_height_0_subtile_0__pin_I_2_}]
set_load -pin_load 0.0334 [get_ports {top_grid_bottom_width_0_height_0_subtile_0__pin_I_6_}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[0]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[1]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[2]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[3]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[4]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[5]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[6]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[7]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[8]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[9]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[10]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[11]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[12]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[13]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[14]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[15]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[16]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[17]}]
set_load -pin_load 0.0334 [get_ports {chanx_left_out[18]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[0]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[1]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[2]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[3]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[4]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[5]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[6]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[7]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[8]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[9]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[10]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[11]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[12]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[13]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[14]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[15]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[16]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[17]}]
set_load -pin_load 0.0334 [get_ports {chanx_right_out[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ccff_head}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pReset}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {prog_clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_left_in[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chanx_right_in[18]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
