###############################################################################
# Created by write_sdc
# Fri Dec 30 16:12:23 2022
###############################################################################
current_design cby_4__1_
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name prog_clk -period 20.0000 [get_ports {prog_clk}]
set_clock_transition 0.1500 [get_clocks {prog_clk}]
set_clock_uncertainty 0.2500 prog_clk
set_propagated_clock [get_clocks {prog_clk}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {ccff_head}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[0]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[10]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[11]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[12]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[13]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[14]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[15]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[16]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[17]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[18]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[1]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[2]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[3]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[4]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[5]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[6]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[7]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[8]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_in[9]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[0]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[10]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[11]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[12]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[13]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[14]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[15]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[16]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[17]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[18]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[1]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[2]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[3]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[4]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[5]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[6]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[7]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[8]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_in[9]}]
set_input_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {pReset}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {ccff_tail}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[0]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[10]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[11]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[12]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[13]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[14]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[15]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[16]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[17]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[18]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[1]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[2]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[3]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[4]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[5]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[6]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[7]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[8]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_bottom_out[9]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[0]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[10]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[11]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[12]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[13]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[14]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[15]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[16]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[17]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[18]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[1]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[2]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[3]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[4]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[5]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[6]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[7]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[8]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {chany_top_out[9]}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {left_grid_right_width_0_height_0_subtile_0__pin_I_1_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {left_grid_right_width_0_height_0_subtile_0__pin_I_5_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {left_grid_right_width_0_height_0_subtile_0__pin_I_9_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {right_grid_left_width_0_height_0_subtile_0__pin_outpad_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {right_grid_left_width_0_height_0_subtile_1__pin_outpad_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {right_grid_left_width_0_height_0_subtile_2__pin_outpad_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {right_grid_left_width_0_height_0_subtile_3__pin_outpad_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {right_grid_left_width_0_height_0_subtile_4__pin_outpad_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {right_grid_left_width_0_height_0_subtile_5__pin_outpad_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {right_grid_left_width_0_height_0_subtile_6__pin_outpad_0_}]
set_output_delay 4.0000 -clock [get_clocks {prog_clk}] -add_delay [get_ports {right_grid_left_width_0_height_0_subtile_7__pin_outpad_0_}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {ccff_tail}]
set_load -pin_load 0.0334 [get_ports {left_grid_right_width_0_height_0_subtile_0__pin_I_1_}]
set_load -pin_load 0.0334 [get_ports {left_grid_right_width_0_height_0_subtile_0__pin_I_5_}]
set_load -pin_load 0.0334 [get_ports {left_grid_right_width_0_height_0_subtile_0__pin_I_9_}]
set_load -pin_load 0.0334 [get_ports {right_grid_left_width_0_height_0_subtile_0__pin_outpad_0_}]
set_load -pin_load 0.0334 [get_ports {right_grid_left_width_0_height_0_subtile_1__pin_outpad_0_}]
set_load -pin_load 0.0334 [get_ports {right_grid_left_width_0_height_0_subtile_2__pin_outpad_0_}]
set_load -pin_load 0.0334 [get_ports {right_grid_left_width_0_height_0_subtile_3__pin_outpad_0_}]
set_load -pin_load 0.0334 [get_ports {right_grid_left_width_0_height_0_subtile_4__pin_outpad_0_}]
set_load -pin_load 0.0334 [get_ports {right_grid_left_width_0_height_0_subtile_5__pin_outpad_0_}]
set_load -pin_load 0.0334 [get_ports {right_grid_left_width_0_height_0_subtile_6__pin_outpad_0_}]
set_load -pin_load 0.0334 [get_ports {right_grid_left_width_0_height_0_subtile_7__pin_outpad_0_}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[0]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[1]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[2]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[3]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[4]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[5]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[6]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[7]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[8]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[9]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[10]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[11]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[12]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[13]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[14]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[15]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[16]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[17]}]
set_load -pin_load 0.0334 [get_ports {chany_bottom_out[18]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[0]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[1]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[2]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[3]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[4]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[5]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[6]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[7]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[8]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[9]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[10]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[11]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[12]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[13]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[14]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[15]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[16]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[17]}]
set_load -pin_load 0.0334 [get_ports {chany_top_out[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ccff_head}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pReset}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {prog_clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_bottom_in[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {chany_top_in[18]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
